sudo: required
services:
    - docker

before_install:
    - docker build -t abhinav/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true abhinav/react-test npm test

after_success:
    - docker build -t abhinavsreesan/multi-client ./client
    - docker build -t abhinavsreesan/multi-nginx ./nginx
    - docker build -t abhinavsreesan/multi-server ./server
    - docker build -t abhinavsreesan/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push abhinavsreesan/multi-client
    - docker push abhinavsreesan/multi-nginx
    - docker push abhinavsreesan/multi-server
    - docker push abhinavsreesan/multi-worker
    
deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-1
    app: mulit-docker
    env: MulitDocker-env
    bucket_name: elasticbeanstalk-us-east-1-647779441057
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY